name: kurdish_tv_app
description: A new Flutter project for Kurdish TV Web App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  firebase_core: any
  cloud_firestore: any
  firebase_database: any
  video_player: any
  chewie: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/
